### ISSUE TITLE
Access underlying ResponseWriter from transaction.

### ISSUE THREAD

**Issue by cdavistk** [newrelic/go-agent#102]
We use NewRelic by adding a handler that calls `StartTransaction` with our ResponseWriter, that has already been wrapped by another type. We need to be able to access that type at other points downstream from this handler, but the only way to do that would be to have a method on the Transaction to access the underlying ResponseWriter. I can make a PR to add this functionality, if everyone thinks that makes sense.

**Comment by rittneje** [comment]
I don't know the specifics of your use case, but would be possible to instead just invert the ordering of the wrappers? That is, can you instead wrap the New Relic `http.ResponseWriter` inside your custom type?

**Comment by cdavistk** [comment]
That's a good idea. I will have to look into the ease of doing that. Thanks for the feedback!

**Comment by kevburnsjr** [comment]
Have you considered adding a reference to your ResponseWriter in the request context? See `newrelic.FromContext` for an example.

This issue smells a lot like a similar problem I've had and the conclusion I came to is that this class of problems is caused by users type casting the ResponseWriter in their http handlers. More details [here](https://github.com/kevburnsjr/microcache/issues/10#issuecomment-534806688) on why it's a bad idea.

**Comment by rittneje** [comment]
@kevburnsjr While I think that approach can work well in some use cases, it's not always a good idea. For example, let's suppose that the custom writer got wrapped inside the New Relic writer. If you were to just pull the custom writer out of the context and use it, none of your method calls would flow through the New Relic one, potentially causing an issue.
Plus, I'm not sure what your describing technically satisfies the LSP anyway. Your `http.Handler` implementation would effectively impose a new precondition that the context contain a reference to the custom writer, violating the "preconditions cannot be strengthened in a subtype" clause.

**Comment by kevburnsjr** [comment]
Based on his problem statement, it sounds like that's exactly the behavior he's looking for :man_shrugging: 

Perhaps you're right that it's just another precondition. Still, adding to the context feels much less egregious than a type assertion against a method argument that materially changes the behavior of the function. The pattern in this example hides critical functionality behind an optional interface ensuring this middleware will inevitably be incompatible with some other middleware if used in this way. 

Seems to me that the request context exists specifically to encapsulate these types of details and should be the documented source of transaction references in order to prevent similar problems for customers in the future.

**Comment by rittneje** [comment]
To clarify, I 100% agree that pulling the transaction from the context is the better approach in general, and that having `Transaction` extend `http.ResponseWriter` was probably a mistake. But the original question wasn't about transactions per se, it was about dealing with some other custom response writer. So if the use case is more along the lines of "I need to call methods that are orthogonal to the response writer methods" (meaning that the type in question didn't really need to extend `http.ResponseWriter`), then absolutely using the context works nicely. But if the use case is "I need to call a method that in turn calls response writer methods" then using the context may not be the best choice.
