### ISSUE TITLE
Document use of txn.NewGoroutine() with contexts

### ISSUE THREAD

**Issue by edmorley** [newrelic/go-agent#120]
Hi!

The docs [here](https://docs.newrelic.com/docs/agents/go-agent/instrumentation/instrument-go-transactions#h2-monitor-a-transaction-with-multiple-goroutines) mention the need to use `txn.NewGoroutine()` when monitoring a transaction across multiple goroutines.

However the examples all involve passing `newrelic.Transaction`s around, whereas in an app I'm trying to instrument, it passes `context.Context`s everywhere, and uses `newrelic.FromContext()` when we need the actual transaction.

I'm still new to Go, so I apologise if these are a silly questions, but:
1. Do I still need to use `txn.NewGoroutine()` when the transaction was passed to the new goroutine inside a context, given that the [Go context docs](https://golang.org/pkg/context/) say:

   >  The same Context may be passed to functions running in different goroutines; Contexts are safe for simultaneous use by multiple goroutines. 

2. If it is still necessary, is there a cleaner pattern I can use other than this?

   ```go
   txn := newrelic.FromContext(ctx)
   ctx = newrelic.NewContext(ctx, txn.NewGoroutine())
   ```

Many thanks :-)

**Comment by willnewrelic** [comment]
> Do I still need to use txn.NewGoroutine() when the transaction was passed to the new goroutine inside a context

Yes.  (There is no way for us to detect that the context was passed and call `NewGoroutine` automatically)

> If it is still necessary, is there a cleaner pattern I can use other than this?

Unfortunately, that's the only way to do it.  We acknowledge that this is awkward!  It looks like it would be nice for us to provide a helper function like this:

```
func NewGoroutineContext(ctx context.Context) context.Context
```

Sorry for the annoyance!

**Comment by purple4reina** [comment]
Hey Ed! Thanks again for all your great questions!

For your first question "Do I still need to use `txn.NewGoroutine()` when the transaction was passed to the new goroutine inside a context", I think a good way to better understand is to think of the Context kind of like a fancy dictionary (it isn't a map type under the hood, but still behaves as such with key/value pairings). With this, the Context itself is goroutine safe. However, the `newrelic.Transaction` that is a value in the Context is not 100% goroutine safe. So, you can pass the Transaction between goroutines just fine in the Context, but once you need to use that Transaction, you must use a little care.

This all stems from how the `newrelic.Transaction` keeps track of segments. It uses a stack of segments, adding them on when they are created and popping them off when they have ended. This means that things can break in weird ways when trying to do asynchronous work in goroutines. When calling `txn.NewGoroutine()`, a completely new segment stack is created. Note that this behavior is different depending on the New Relic language agent. The Python agent for example does not maintain a stack at all for segments, it instead acts more like a linked list.

As Will already mentioned, your example as part of your second question is correct. We'd be more than happy to entertain an added or improved API based on your usage and feedback! If you come up with something that works well for you, post it to this Issue. We might consider adding it to the agent, and in the least, it will help others with the same questions.

Take care,
Rey

**Comment by edmorley** [comment]
Thank you for the fast response and detailed answers - helped build up my mental model a bit more :-)

I like the sound of a potential `NewGoroutineContext()` or similar (my initial draft of the OP asked about possibly adding a helper to the agent and also used the same `NewGoroutineContext` name as the example hehe) - I'll have a play around and see what might feel right from an API point of view.

**Comment by edmorley** [comment]
Yeah your idea feels right in terms of API, from trying it locally:

```diff
diff --git a/v3/newrelic/context.go b/v3/newrelic/context.go
index 96537c6..0164f74 100644
--- a/v3/newrelic/context.go
+++ b/v3/newrelic/context.go
@@ -36,0 +37,8 @@ func FromContext(ctx context.Context) *Transaction {
+// NewGoroutineContext calls NewGoroutine() on any Transaction found within
+// the provided context.Context and returns a copy of the context containing
+// the new transaction reference.
+func NewGoroutineContext(ctx context.Context) context.Context {
+       txn := FromContext(ctx)
+       return NewContext(ctx, txn.NewGoroutine())
+}
+
```

If this were also going to be added to the v2 version of the agent (and not just v3), I'm presuming there would need to be an additional nil-check on `txn`.

**Comment by mmacheerpuppy** [comment]
@willnewrelic 

Hi Will,

Is this design pattern taken into account with the NR Gorilla helper, in general a new goroutine is spawned for each Serve HTTP call.

**Comment by newrelic-eheinlein** [comment]
Hi @mmacheerpuppy, thanks for the question! The nrgorilla integration does take this pattern into account. In that case we don't need to call `txn.NewGoroutine` because each nrgorilla transaction is started within the goroutine after it has already been spawned.  You only need to worry about this kind of issue when the transaction crosses goroutine boundaries.

Hope that helps - let us know if you have any further questions!

**Comment by mmacheerpuppy** [comment]
@newrelic-eheinlein Hi, thank you so much for getting back. One problem that I worry about with my current usage is lock contention.  Generally speaking, I have functions of the form... 

```
Google := func(ctx context.Context, query string) ([]Result, error) {
    g, ctx := errgroup.WithContext(ctx)
    searches := []Search{Web, Image, Video}
    results := make([]Result, len(searches))
    for i, search := range searches {
        i, search := i, search // https://golang.org/doc/faq#closures_and_goroutines
        g.Go(func() error {
            
            result, err := search(ctx, query)
            if err == nil {
                results[i] = result
            }
            return err
        })
    }
    if err := g.Wait(); err != nil {
        return nil, err
    }
    return results, nil
}
```

Where `search` will do something along the lines of...

`defer txn.StartSegment("mySegmentName").End()`

The documentation advises, in this case, I should use the NewGoroutine function. However, sometimes due to the codebase I work with, the search method is _not_ called by a Goroutine. Instead, there are situations where the same function is called by a synchronous transaction (so no extra goroutines spawned). By the illustration, we can imagine some API calls would search for many links, and some other API calls will search for a single link. 

I think in these situations, I have been mainly worried about causing lock contention between using the Segment API when instrumenting transactions. I wouldn't want attempts to StartSegment to be blocking until one Segment has finished its work https://github.com/newrelic/go-agent/blob/178f6e3d7e12c08bc840d8d2df3725166dbd407e/v3/newrelic/internal_txn.go#L670.

(a): Is it possible for StartSegment or NewGoroutine.StartSegment to cause lock contention on the transaction or segment level?

(b): Are there any common design patterns which can be useful to instrument DRY code (as mentioned above)? I presume typical advice involves treating segments like wrappers to method calls. But this would be convoluted to instrument as opposed to a simple timer method which could be DRY'd up to, i.e. by the illustration to the `search` method.

(c): So (b) got me thinking about what the methods do, and I started digging around your codebase. All I'm looking to do is acquire the standard deviation of the time it takes method calls to complete for the search method per transaction. Would it then be safe to use New Goroutine.StartSegment to time this function when _not_ spawned within a new goroutine?

This would result in the function being timed using transactions which do and do not spawn GoRoutines depending on the use case of the function (per the illustration). Are there any the downsides in doing this? Is it possible for other timings (like the request timing) to be inaccurate or lock contention to occur if the transaction has not been spawned in a new thread?

Thank you for your excellent customer service as always. I have been using New Relic across clients for years now, but this is my first encounter with your Go service!

**Comment by mmacheerpuppy** [comment]
For what its worth I do think that my questions fold within this issue as they are related to txn.NewGoroutine() design patterns!
