### ISSUE TITLE
Instrumenting Middleware with nrgorilla integration

### ISSUE THREAD

**Issue by beanieboi** [newrelic/go-agent#124]
Hey all 👋 

thank you for making `v3` a reality, it really makes things easier. especially by supporting configuration through ENV vars to match the usability of other NewRelic agents.

i'm running in a problem tho. We are using `gorilla/mux` together with `braintree/manners` (shouldn't matter too much) and we are using the `nrgorilla` integration.

I want to be able to instrument some of our custom middleware but i'm unable to fetch the transaction back from the context.

I isolated the code by using your example from https://github.com/newrelic/go-agent/blob/master/v3/integrations/nrgorilla/example/main.go
Full example at the end.

My middleware looks like this (based on the official gorilla/mux docs https://github.com/gorilla/mux#middleware)

```golang
func customMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		txn := newrelic.FromContext(r.Context())
		segment := txn.StartSegment("customMiddleware")

		time.Sleep(50 * time.Millisecond)
		segment.End()

		next.ServeHTTP(w, r)
	})
}
```

I'm not sure why the transaction is not part of the context.
If i use my own middleware for NewRelic instrumentation instead of the `nrgorilla` integration, it works as expected.

my custom NewRelic middleware looks like this:

```golang
func newrelicMiddleware(app *newrelic.Application) mux.MiddlewareFunc {
 	return func(next http.Handler) http.Handler {
 		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
 			// snip more code...
 			txn := app.StartTransaction(txnName)
 			w = txn.SetWebResponse(w)
 			txn.SetWebRequestHTTP(r)

 			defer txn.End()
 			r = newrelic.RequestWithTransactionContext(r, txn)
 			next.ServeHTTP(w, r)
 		})
 	}
 }
```

We really don't want to maintain our own middleware and would love to get this working with the official `nrgorilla` integration.

Full example
```golang
package main

import (
	"fmt"
	"net/http"
	"os"
	"time"

	"github.com/gorilla/mux"
	"github.com/newrelic/go-agent/v3/integrations/nrgorilla"
	"github.com/newrelic/go-agent/v3/integrations/nrlogrus"
	"github.com/newrelic/go-agent/v3/newrelic"
)

func makeHandler(text string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(text))
	})
}

func customMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		txn := newrelic.FromContext(r.Context())
		segment := txn.StartSegment("customMiddleware")

		time.Sleep(50 * time.Millisecond)
		segment.End()

		next.ServeHTTP(w, r)
	})
}

func main() {
	app, err := newrelic.NewApplication(
		newrelic.ConfigDistributedTracerEnabled(true),
		nrlogrus.ConfigStandardLogger(),
		func(cfg *newrelic.Config) {
			cfg.ErrorCollector.RecordPanics = true
		},
		newrelic.ConfigFromEnvironment(),
	)

	if nil != err {
		fmt.Println(err)
		os.Exit(1)
	}

	r := mux.NewRouter()
	r.Handle("/", makeHandler("index"))
	r.Handle("/alpha", makeHandler("alpha"))

	users := r.PathPrefix("/users").Subrouter()
	users.Handle("/add", makeHandler("adding user"))
	users.Handle("/delete", makeHandler("deleting user"))

	// The route name will be used as the transaction name if one is set.
	r.Handle("/named", makeHandler("named route")).Name("special-name-route")

	// The NotFoundHandler will be instrumented if it is set.
	r.NotFoundHandler = makeHandler("not found")

	r.Use(customMiddleware)

	http.ListenAndServe(":8080", nrgorilla.InstrumentRoutes(r, app))
}

```

I'm happy for any hint.

Cheers and thanks again
Ben

**Comment by edmorley** [comment]
It looks like mux invokes middleware before calling handlers on a route (which I guess makes sense, since it's middleware):
https://github.com/gorilla/mux/blob/49c01487a141b49f8ffe06277f3dca3ee80a55fa/mux.go#L136-L142

The `nrgorilla` integration instruments mux by wrapping the route handlers:
https://github.com/newrelic/go-agent/blob/3f901151beadf80f772132193d5bb2fcbd3df469/v3/integrations/nrgorilla/nrgorilla.go#L66-L68

...which means the instrumentation is called after the middleware has already run.

It seems like the way to solve this would be for `nrgorilla` to return a custom `http.Handler` that wrapped the router's `ServeHTTP`. The New Relic transaction would need to be started in the handler's `ServeHTTP` prior to calling the original router's `ServeHTTP`, and then presumably the transaction name updated inside the instrumented routes (since the exact name wouldn't be known at that point).

Or alternatively perhaps the instrumentation could occur in middleware (that way no need to separate the transaction creation and final naming), however that would mean the method not allow and not found handlers wouldn't be instrumented unless additional steps were taken, since they aren't invoked with middleware:
https://github.com/gorilla/mux/blob/49c01487a141b49f8ffe06277f3dca3ee80a55fa/mux.go#L202-L208

**Comment by purple4reina** [comment]
Hey @beanieboi!

Thanks a ton for opening this issue! It's certainly suboptimal that we're not able to have access to the transaction from within a custom middleware. It seems @edmorley is correct, the transaction is starting on the handler level, not the middleware level. What's more is that our gorilla instrumentation isn't monitoring any of your middleware, meaning you could have a big slow down or an error or what not in your middleware and you'd have no way of knowing!

It looks like this design decision was made because our nrgorilla instrumentation was created in 2016, but gorilla didn't add middleware support (through `r.Use`) until [v1.6.1 in 2018](https://github.com/gorilla/mux/releases/tag/v1.6.1).

I'll do more research and discuss this with our team and see what we can do to get these middlewares instrumented! I'll report back when I have more information for you.

Thanks again!

**Comment by beanieboi** [comment]
@purple4reina Would you accept a PR that moves `nrgorilla` closer to `nrgin` (https://github.com/newrelic/go-agent/tree/master/v3/integrations/nrgin) which provides a middleware?

**Comment by purple4reina** [comment]
> @purple4reina Would you accept a PR that moves `nrgorilla` closer to `nrgin` (https://github.com/newrelic/go-agent/tree/master/v3/integrations/nrgin) which provides a middleware?

@beanieboi You're the best, but no worries though, I spent yesterday looking into this and discussing it with the team. Here's the diff I'm thinking of:

```diff
diff --git a/v3/integrations/nrgorilla/nrgorilla.go b/v3/integrations/nrgorilla/nrgorilla.go
index 081147d..3d7c29d 100644
--- a/v3/integrations/nrgorilla/nrgorilla.go
+++ b/v3/integrations/nrgorilla/nrgorilla.go
@@ -23,13 +23,14 @@ type instrumentedHandler struct {
 }
 
 func (h instrumentedHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
-	name := routeName(r)
-	txn := h.app.StartTransaction(name)
-	txn.SetWebRequestHTTP(r)
-	w = txn.SetWebResponse(w)
-	defer txn.End()
-
-	r = newrelic.RequestWithTransactionContext(r, txn)
+	if newrelic.FromContext(r.Context()) == nil {
+		name := routeName(r)
+		txn := h.app.StartTransaction(name)
+		txn.SetWebRequestHTTP(r)
+		w = txn.SetWebResponse(w)
+		defer txn.End()
+		r = newrelic.RequestWithTransactionContext(r, txn)
+	}
 
 	h.orig.ServeHTTP(w, r)
 }
@@ -74,3 +75,17 @@ func InstrumentRoutes(r *mux.Router, app *newrelic.Application) *mux.Router {
 	}
 	return r
 }
+
+func Middleware(app *newrelic.Application) mux.MiddlewareFunc {
+	return func(next http.Handler) http.Handler {
+		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+			name := routeName(r)
+			txn := app.StartTransaction(name)
+			defer txn.End()
+			txn.SetWebRequestHTTP(r)
+			w = txn.SetWebResponse(w)
+			r = newrelic.RequestWithTransactionContext(r, txn)
+			next.ServeHTTP(w, r)
+		})
+	}
+}
```

Essentially, we'll add the middleware just as you've proposed and make one small change to the existing `InstrumentRoutes` to prevent double instrumenting in case people continue to use `InstrumentRoutes` along with the new middleware.

I'm working on tests now. Any thoughts on this in the meantime?

**Comment by beanieboi** [comment]
@purple4reina the middleware looks good to me!

**Comment by purple4reina** [comment]
Hey @beanieboi I haven't forgotten about you. I'm working on this now and we'll be getting it out to you soon.

**Comment by willnewrelic** [comment]
Hi @beanieboi 

We just release `v3/integrations/nrgorilla/v1.1.0` which has gorilla middleware support!  Take a look:  https://github.com/newrelic/go-agent/blob/master/CHANGELOG.md#320

Thanks for bringing this to our attention.
