### ISSUE TITLE
Integration accesses internal packages.

### ISSUE THREAD

**Issue by nicolas-martin** [newrelic/go-agent#132]
Hi, I'd like to contribute and add a snowflake integration. However, since I forked the repo, I am not able to compile my module as it requires access to packages inside `/internal`.

In order to get this working, I had to clone the repo, create a new branch with my changes and use a local replace in my app. But isn't really viable in a production environment.

I plan on creating a PR and submitting my changes soon but ideally I would be able to use it myself without having to wait for the PR, merge and release of the go-agent package.

**Comment by purple4reina** [comment]
Hey @nicolas-martin, thanks for submitting this issue! Which parts of the `internal` package in particular are you looking to have access to?

**Comment by nicolas-martin** [comment]
My changes were heavily inspired by the [mysql integration](https://github.com/newrelic/go-agent/blob/master/v3/integrations/nrmysql/nrmysql.go). I need `github.com/newrelic/go-agent/v3/internal`, `github.com/newrelic/go-agent/v3/internal/sqlparse`

**Comment by purple4reina** [comment]
Cool, that's what I suspected. Let me bring this to the team and see what we can do to help you out. In the meantime, thanks a ton for working on a Snowflake integration! I look forward to seeing it!

**Comment by nicolas-martin** [comment]
Yup, I was able to test it in our newrelic instance. We don't get as much details as mysql does, but I do get query names and timing. Which is good enough for now.

**Comment by purple4reina** [comment]
@nicolas-martin,

An update for you. We've decided to go ahead and move the `ParseQuery` code out of the `internal` package! 🎉 It'll be available in our next release.

As for your snowflake integration and use of the `ParseQuery` code (which for the record I have not looked at your PR yet), my one concern about you using the `ParseQuery` would be for security reasons. It is important that we do not send any more than table names and column names. I would be concerned that because snowflake is not exactly the same language as mysql, postgres, or sqlite, that our regexes might behave in strange ways. Anyway, that's what I'll be looking at as I review that PR, but I wanted to include it here too so others reading this can be aware.

More soon,
Rey

**Comment by purple4reina** [comment]
@nicolas-martin, we just released a version of the go-agent with the `ParseQuery` code made public. Thanks again for your suggestion and contributions!

**Comment by nicolas-martin** [comment]
Thank you for the quick turn around!

**Comment by purple4reina** [comment]
@nicolas-martin,

Sharp eye you have 😉. We've decided to leave that one as internal because it is not required at all for you to get the full experience in APM from your datastore metrics. We just use that metric internally to track usage and uptake of our integration packages.
