### ISSUE TITLE
Newrelic Golang Agent Support for sqlx (mysql)

### ISSUE THREAD

**Issue by komalbb** [newrelic/go-agent#152]
Hi, Does Newrelic golang agent support mysql Sqlx? If not, is there a plan to support it?
If it's supported already, an example will be greatly helpful.

**Comment by purple4reina** [comment]
Hey @komalbb! The Go Agent does in fact support sqlx with mysql. Take a look at this example that uses postgres. https://github.com/newrelic/go-agent/blob/master/v3/integrations/nrpq/example/sqlx/main.go

To use mysql instead of postres in the example, you'll want to make just two changes to the code. First, change the import from `_ "github.com/newrelic/go-agent/v3/integrations/nrpq"` to `_ "github.com/newrelic/go-agent/v3/integrations/nrmysql"`. Then, change `db, err := sqlx.Connect("nrpostgres", "user=foo dbname=bar sslmode=disable")` to `db, err := sqlx.Connect("mymysql", "user=foo dbname=bar sslmode=disable")` with whatever username/password is required for your mysql server.

Then, you'll notice that you will be required to provide a context with a transaction to all database calls. This means changing calls to `db.Get` to `db.GetContext`.

I'm going to go ahead and close out this issue, but we really appreciate you opening it! Let us know here if you have any further questions. We're always happy to help.

**Comment by soichisumi** [comment]
@purple4reina Hi, I've run the example but a span for GetContext seems not shown. Am i missing something?

sample: 
https://github.com/soichisumi/go-snippets/blob/master/lib/newrelic/newrelic.go
result:
Only the span of GetContext is missing
![image](https://user-images.githubusercontent.com/30210641/90328465-8f198b00-dfd7-11ea-9b40-993c28d24e57.png)
