### ISSUE TITLE
Expose httpClient in v3 go-agent

### ISSUE THREAD

**Issue by yuanmwang-wf** [newrelic/go-agent#154]
We recently ran into problems described in https://github.com/golang/go/issues/33006 where a bad connection could potentially block all outgoing http requests from an application. 

We discovered the default client created by `http.DefaultClient` contains some shared/global state and any library may assume they were only modifying one http client when it unfortunately modifies all http clients in an app, for more of this please see https://github.com/hashicorp/go-cleanhttp. 

A workaround for this is to set up custom `http.Transport` and then pass the transport to a custom `http.Client` with sane timeouts, however, right now we can only pass a custom transport [here](https://github.com/newrelic/go-agent/blob/v3.5.0/v3/newrelic/config.go#L163-L165) but we're not able to pass a custom client to the v3 agent. Is it possible to expose the http client used in v3 agent so we can pass our own custom client?

**Comment by purple4reina** [comment]
@yuanmwang-wf Thank you so much for opening this issue. We really appreciate that you've included the link to [golang/go#33006](https://github.com/golang/go/issues/33006) as well. I believe we have all we need in order to reproduce this and get to a solution for you.

That being said, would you feel happy if instead of exposing the `http.Client` we instead simply stop using the `http.DefaultClient`?

Take good care,
Rey

**Comment by yuanmwang-wf** [comment]
>That being said, would you feel happy if instead of exposing the http.Client we instead simply stop using the http.DefaultClient?

Yes, that works for us.

**Comment by purple4reina** [comment]
Hi @yuanmwang-wf I've opened a PR with some proposed changes that should address this issue. We'll get a release out shortly, but I wanted to give you access to this in the meantime. https://github.com/newrelic/go-agent/pull/163
