### ISSUE TITLE
Segments from goroutines not nested

### ISSUE THREAD

**Issue by charleskorn-x** [newrelic/go-agent#168]
I have an application that runs two operations in parallel using separate goroutines.

I start a segment with `newrelic.StartSegment(txn, "Outer")` before starting either goroutine, then call `End()` after both finish.

For each goroutine, I call `txn.NewGoroutine()` to create a goroutine-specific transaction, then use that new transaction to create a segment to measure the time spent in the goroutine (`Operation 1` and `Operation 2`).

I'd expect `Operation 1` and `Operation 2` to be nested within `Outer` in the New Relic UI, but they appear as parallel spans in the transaction view:

<img width="558" alt="Screen Shot 2020-07-03 at 2 38 52 pm" src="https://user-images.githubusercontent.com/53165929/86432595-9f351e00-bd3b-11ea-97a7-af2677c0a399.png">

(I've had to redact the screenshot to hide sensitive information)

Spans started within each goroutine (eg. the two database calls in the screenshot above) are correctly nested.

https://github.com/newrelic/go-agent/issues/120#issuecomment-564212204 seems to be related:

> ...
>
> This all stems from how the newrelic.Transaction keeps track of segments. It uses a stack of segments, adding them on when they are created and popping them off when they have ended. This means that things can break in weird ways when trying to do asynchronous work in goroutines. When calling txn.NewGoroutine(), a completely new segment stack is created. Note that this behavior is different depending on the New Relic language agent. The Python agent for example does not maintain a stack at all for segments, it instead acts more like a linked list.
>
> ...

Is there a reason why the segment stack isn't maintained across goroutines?

**Comment by charleskorn-x** [comment]
This also seems to affect the calculation of transaction latencies - we're now seeing transaction latencies being reported that don't seem to take into account the nesting of the goroutines within the transaction (the values reported as metrics look correct).

**Comment by purple4reina** [comment]
Hi @charleskorn-x,

Thanks for opening this issue. I'll do my best to explain our decision making in how we designed the `NewGoroutine`. What it comes down to tracking exclusive time. Exclusive time is an important piece of all the metrics that New Relic reports, so it's vital we get it right. It's real easy to do when the work is synchronous: just subtract the duration of all children from the parent to arrive at exclusive time. However, this falls apart when we get to asynchronous work. What if a segment has multiple overlapping children? What if the children run longer than the parent? There's no great way to answer this. We discussed the implementation with other New Relic agent teams, primarily the Python Agent which does support async work. Those teams shared with us their difficulties and how they continually are hitting bugs and issues. In order to avoid these, we decided to release with what you see here as a good first start.

I totally recognize that the current implementation, which nests segments under the root, does not work for everyone. We're tracking this issue internally as a feature request. We'll let you know when we make progress on it.

> This also seems to affect the calculation of transaction latencies - we're now seeing transaction latencies being reported that don't seem to take into account the nesting of the goroutines within the transaction (the values reported as metrics look correct).

This statement is concerning/interesting to me. Can you share what you mean by "transaction latencies"? Which latency value in the UI are you referring to? How does it differ from what you'd expect? Is it longer/shorter than you were expecting?

Hope you are well, I look forward to your reply,

Rey

**Comment by charleskorn-x** [comment]
Hi @purple4reina,

Thanks for your response.

>> This also seems to affect the calculation of transaction latencies - we're now seeing transaction latencies being reported that don't seem to take into account the nesting of the goroutines within the transaction (the values reported as metrics look correct).
>
> This statement is concerning/interesting to me. Can you share what you mean by "transaction latencies"? Which latency value in the UI are you referring to? How does it differ from what you'd expect? Is it longer/shorter than you were expecting?

When I say transaction latencies, I'm referring to the `duration` attribute on `Transaction` events. It is longer than what we expect - the values we're seeing in New Relic contradict what we're seeing from our load test client and the timing data we log in our logs.

**Comment by charleskorn-x** [comment]
Scratch that, I've just realised some of our graphs were using the wrong metric to graph latency (`totalTime` instead of `duration`) - using `duration` produces results that match up with what we expect.

**Comment by purple4reina** [comment]
I'm glad you were able to figure it out! Yes, the difference between `totalTime` and `duration` is an important one to point out. `duration` is the time spent from when the request is received to when the response is sent. `totalTime` on the other hand is `duration` _plus_ time spent in any goroutines.

Take good care,
Rey
