### ISSUE TITLE
Cross Application Tracing Support

### ISSUE THREAD

**Issue by lattwood** [newrelic/go-agent#22]
golang is a great microservice language, and there would be immense value in supporting Cross Application Tracing in that context, even if it means manually extracting/adding the `X-NewRelic-*` headers to http requests.

**Comment by lpetre** [comment]
The [Android SDK](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/work-android-sdk-api#pre34) has `Agent.getCrossProcessId` which enables you to track HTTP calls between applications. I'd love to see something similar in this package, or something similar, so that I can augment calls that go between APM applications.

**Comment by willnewrelic** [comment]
Hi lattwood

Thanks for the cross app tracing support interest.  This is definitely on our roadmap!

**Comment by jippi** [comment]
Any update on this @willnewrelic ?

**Comment by sergeylanzman** [comment]
@willnewrelic You have documentions about this? Maybe I try create support for this.

**Comment by belimawr** [comment]
I agree that it would be a grate improvement!!!

I also agree with @lattwood even adding the headers manually wold be very helpful

**Comment by sergeylanzman** [comment]
@willnewrelic Any update? You can write about header I want add this manually. We really need this.

**Comment by belimawr** [comment]
+1

I really need this feature as well! Even if I have to add the headers manually it would be extremely helpful.

**Comment by belimawr** [comment]
@willnewrelic any updates on this?

**Comment by fbjork** [comment]
@willnewrelic Any update?

**Comment by zapient** [comment]
+1 Would love this to be added

**Comment by lattwood** [comment]
Just added this feature to DataDog's APM on a fork, for those still looking for this.

https://github.com/securityscorecard/dd-trace-go/commit/08a49a15721a30231ef41144a6ea8eb850d04d22

**Comment by nadavshatz** [comment]
👍

**Comment by iaroslav-ciupin** [comment]
+1 @willnewrelic Is there any progress on this feature? would be great to hear any news

**Comment by robertnewrelic** [comment]
Hey everyone!  Thanks for you interest in adding Cross Application Tracing support to our Go agent.  We have a feature request opened internally and are actively working on its implementation as I write this.  I do not yet have an ETA for when it will be released, but know that it's coming soon!

**Comment by nadavshatz** [comment]
@robertnewrelic why did you close the issue before the functionality is available?

**Comment by robertnewrelic** [comment]
@nadavshatz You have a good point, let me reopen the issue until the functionality is available.  I had initially closed it as 'being an issue' since it is actively being worked on internally, but I realize I don't want to give the impression to the community that the issue is not being addressed.

Thank you for the feedback!

**Comment by LawnGnome** [comment]
We have just released version 1.11 with CAT support — please give it a whirl!
