### ISSUE TITLE
Swallowed Panic Traces

### ISSUE THREAD

**Issue by matthinrichsen-wf** [newrelic/go-agent#275]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

https://github.com/newrelic/go-agent/blob/master/internal_txn.go#L424-L475 causes the stack trace which caused the panic to be lost. 

## Steps to Reproduce

Cause a panic between `transaction.Start` and `defer transaction.End()` and note that the reported stack trace is missing the original line which caused the error.

## Expected Behavior

Either:
The original stack trace should be emitted as a log `string(debug.Stack())`

Or:
The panic should not be caught and callers should be expected to handle panics

**Comment by RichVanderwal** [comment]
Pending March Go Agent Maintenance Release.

**Comment by RichVanderwal** [comment]
Hello, @matthinrichsen-wf !

Yesterday's Go Agent Release (v3.11.0) should address this ticket. The change we made in PR #278 is what you suggested, and now the agent logs stack traces when the `cfg.ErrorCollector.RecordPanics` setting is true.

Note that the stack trace produced will have a few more frames at the top than what would otherwise be produced, reflecting our RecordPanics instrumentation, so if you have any automated log processing, you may want to adjust as necessary.
