### ISSUE TITLE
Repair nrgraphgophers integration test

### ISSUE THREAD

**Issue by RichVanderwal** [newrelic/go-agent#307]
GitHub Actions won't run the nrgraphgophers test successfully, although it runs fine on our workstations and on a standalone AWS EC2 node with Go 1.16.1.

Find out why it's not passing in GHA and fix it.

**Comment by iamemilio** [comment]
Reproduced locally with this dockerfile:

```dockerfile
FROM golang:1.15
ENV DIRS=v3/integrations/nrgraphgophers
ENV EXTRATESTING='go get -u github.com/graph-gophers/graphql-go@master'
CMD cd /go-agent; ./build-script.sh;
```

**Comment by iamemilio** [comment]
The error type has changed, which is why the test is failing: `expect_implementation.go:27: traced errors klass *errors.QueryError *errors.errorString`

got: `*errors.errorString`
want: `*errors.QueryError`

Also, I'd like to make the message and usage of the `validateStringField` function in `v3/newrelic/expect_implementation.go` more consistent. It does not clearly indicate what value is expected, and what value it got. Also the usage flips these values all over the place, adding to the confusion.

```golang
func validateStringField(v internal.Validator, fieldName, v1, v2 string) {
	if v1 != v2 {
		v.Error(fieldName, v1, v2)
	}
}
```
