### ISSUE TITLE
External Services shows up as "unknown" if no Request is provided.

### ISSUE THREAD

**Issue by klauspost** [newrelic/go-agent#33]
It seems like "External Services" does not use the URL provided if Request is not set:

Simplified usage:
```
func BenchExternal(ctx context.Context, host string, f func()) {
	tx := newRelicTx(ctx)
	defer newrelic.ExternalSegment{
		StartTime: newrelic.StartSegmentNow(tx),
		URL:       host,
	}.End()
	f()
```

I know this isn't the recommended way of doing external segments, but when using API packages that is commonly what we have available. The URL field states:

```Go
	// If you do not have access to the request, this URL field should be
	// used to indicate the endpoint.
	URL string
```

In New Relic these all show up as "External service: unknown" when using "abc.def.com" for instance. Are there special requirements we need to fulfill for this field to be transferred?

**Comment by willnewrelic** [comment]
Hi Klaus

If the `URL` field is populated, the host is parsed out using the standard library's `url.Parse`.  This function requires the `http://` protocol to be present.  [relevant code](https://github.com/newrelic/go-agent/blob/7d12ae2201fc160e486197614a6f65afcf3f8170/internal_txn.go#L467).  Due to your example "abc.def.com" which does not have a protocol, I'm guessing this is the problem?

This requirement should be better documented.  I will fix that for the next release.

**Comment by willnewrelic** [comment]
1.6.0 released with the following documentation added to `ExternalSegment.URL`:

"NOTE: If non-empty, this field is parsed using url.Parse and therefore it MUST include the protocol (eg. "http://")".

I hope this helps!
