### ISSUE TITLE
use of internal package github.com/newrelic/go-agent/v3/internal not allowed

### ISSUE THREAD

**Issue by speedwheel** [newrelic/go-agent#334]
I get this error while trying to run my app.

I am using go1.16.5 windows/amd64 with gomod enabled.

These are my import paths:
```
	"github.com/newrelic/go-agent/v3/internal"
	"github.com/newrelic/go-agent/v3/newrelic"
```

**Comment by nr-swilloughby** [comment]
Can you give us a little insight into what you are trying to get to inside the internal parts of the go agent? That will help us better advise you on how to get what you need.

**Comment by RichVanderwal** [comment]
Hi @speedwheel , we'd love to get input from you on this! Otherwise, we'll close this issue in a week.

**Comment by pete911** [comment]
Hi @nr-swilloughby, @RichVanderwal. I think @speedwheel is trying to import `internal` package which is not allowed. This is go feature - https://golang.org/doc/go1.4#internalpackages
so I don't think there is anything for new relic to do.

**Comment by nr-swilloughby** [comment]
Since we didn't receive input that there was more to this issue that we weren't aware of, we're going to assume the issue in question here is how to import an internal package which Go doesn't allow, and close the ticket. If there's some other way we can be of assistance please don't hesitate to reach out again.
