### ISSUE TITLE
nrlogrusplugin not populating logrus logs for any log produced before an actual request

### ISSUE THREAD

**Issue by ivan-santos-eq** [newrelic/go-agent#539]
## Description
The plugin only starts working when a middleware/request is in place. 

## Steps to Reproduce

Configure logrusplugin, generate some logs before any context/transation setup.

## Expected Behavior

Logs are produced and associated to APM service even when there is no tracing data yet.

## Tip

Some of the Metadata should be able to be injected without Context usage. Service Name for instance should always be included regardless of context. Introspection could happen by passing the Agent instead of context.

**Comment by iamemilio** [comment]
I'm not sure I fully understand the issue. Do you want the logs in context log decorator for logurs to work outside of a newrelic transaction?

**Comment by ivan-santos-eq** [comment]
@iamemilio yes. Only for:
```
metadata.EntityName
metadata.EntityType
metadata.EntityGUID
metadata.Hostname
```
Why?
For logs to show up in the APM page for the app, they need at least `service_name`. If a service identifier is not present as a property of the structured log, it will not show up there.

If I go directly to `logs` general page it might show up there because there's no association with APM.

**Comment by ivan-santos-eq** [comment]
That's the current behavior for instrumentations in dynamic langs such as python (all logs will show up in the APM logs tab).

I've tested adding the service_name property myself and I can confirm it works.

**Comment by iamemilio** [comment]
Good news, that functionality is coming shortly: https://github.com/newrelic/go-agent/pull/538/files#diff-409c7eebb48b281c07b39f130c9efbdb30a7bca1e6116083ee755b3552de032e

**Comment by iamemilio** [comment]
This feature should be live in the 3.18.0 release!

**Comment by ivan-santos-eq** [comment]
@iamemilio thank you very much!

**Comment by iamemilio** [comment]
enjoy, and look out for a log coming soon to walk users through the upgrade process from the old logcontext plugin to the new one

**Comment by iamemilio** [comment]
# Upgrading to logcontext-v2 nrlogrus

The Go agent’s 3.18.0 release adds all of the latest [logs in context features](https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-go/) to a new quick start for the [Logrus logging framework](https://newrelic.com/instant-observability/logrus/075e9126-ea33-44e0-bae4-f7dec0db91fd). The [go agent](https://docs.newrelic.com/docs/apm/agents/go-agent/get-started/go-agent-compatibility-requirements) has supported a plugin for logrus, a structured logger for Go (golang), for quite some time, however,  this new plugin is different in a few notable ways:

- Automatic log forwarding: Ditch the log forwarder, and [view logs in context of APM](https://newrelic.com/blog/nerdlog/apm-logs-in-context) data without any manual configuration by sending logs directly to New Relic with minimal effort.
- Log Metrics: Get a high level summary of the log data you are collecting.
- Local Log Decorating: Decorate your local logs with New Relic linking metadata for use in combination with a [supported log forwarder](https://docs.newrelic.com/docs/logs/forward-logs/enable-log-management-new-relic/#log-forwarding).
- Expanded Log Observability: Observe logs both inside and outside of a transaction.
- Human Friendly Logging: Use the Logrus formatting library of your choice. New Relic linking metadata will be appended to the end of your log message, and will not modify the original log in any other way.


## Setting up Legacy Logging
The legacy Logrus logs in context plugin, named the nrlogrusplugin, is designed as a Logrus formatter. It intercepts each log object before it gets printed, then modifies how it gets printed to your console. The format that it outputs logs as is a JSON format that New Relic’s logging endpoint understands, but note that the logs are not sent to New Relic automatically. They need to be collected by a [supported external log forwarder](https://docs.newrelic.com/docs/logs/forward-logs/enable-log-management-new-relic/#log-forwarding) and sent to New Relic manually. This is an example of how an application could be initialized to use the `nrlogrusplugin`.

```go
package main
 
import (
   "context"
   "os"
   "time"
 
   "github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin"
   newrelic "github.com/newrelic/go-agent/v3/newrelic"
   "github.com/sirupsen/logrus"
)
 
func initializeApp() (*newrelic.Application, *logrus.Logger) {
   app, err := newrelic.NewApplication(
       newrelic.ConfigAppName("Old Logrus Log Decorating"),
       newrelic.ConfigFromEnvironment(),
   )
   if nil != err {
       log.Panic("Failed to create application", err)
   }
 
   log := logrus.New()
   log.SetFormatter(nrlogrusplugin.ContextFormatter{})
 
   return app, log
}
```

## Upgrade to Automatic Log Forwarding
[Automatic log forwarding](https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-go) is the most convenient way to forward logs to New Relic. It requires minimal set up to work, and does not modify how log lines are written, giving you more flexibility in how you choose to log your application. This feature is built into the new logrus formatter, and will require you to upgrade to it, along with the 3.18.0 version of the go agent.

```go
package main
 
import (
   "context"
   "os"
   "time"
 
   "github.com/newrelic/go-agent/v3/integrations/logcontext-v2/nrlogrus"  	(1)
   newrelic "github.com/newrelic/go-agent/v3/newrelic"
   "github.com/sirupsen/logrus"
)
 
func initializeApp() (*newrelic.Application, *logrus.Logger) {
   app, err := newrelic.NewApplication(
       newrelic.ConfigAppName("New Logrus Log Decorating"),
       newrelic.ConfigFromEnvironment(),
       newrelic.ConfigAppLogForwardingEnabled(false),				(2)
   )
   if nil != err {
       log.Panic("Failed to create application", err)
   }
 
   log := logrus.New()
   log.SetFormatter(nrlogrus.NewFormatter(app, &logrus.TextFormatter{}))   	(3)
   log.Info("application connected to New Relic")
 
   return app, log
}
```

First add and import the `nrlogrus` plugin in your application (1). Then, be sure to enable it in your go-agent’s config (2). Once that is done, all you need to do is set the Logrus logger’s formatter to the `nrlogrus` formatter (3). You can use any Logrus formatter you prefer, and because local local log formatting is disabled, the log message will not be modified at all by the `nrlogrus` plugin, making this the most human readable option. 

## Logs in Context Using a Log Forwarder
There are situations where it might be preferable to use a third party [log forwarding](https://docs.newrelic.com/docs/logs/forward-logs/enable-log-management-new-relic/#compatibility-requirements) tool. If this is the case you are just a few easy steps away from upgrading to the latest logs in context plugin for logrus.

```go
package main
 
import (
   "context"
   "os"
   "time"
 
   "github.com/newrelic/go-agent/v3/integrations/logcontext-v2/nrlogrus"	(1)
   newrelic "github.com/newrelic/go-agent/v3/newrelic"
   "github.com/sirupsen/logrus"
)
 
func initializeApp() (*newrelic.Application, *logrus.Logger) {
   app, err := newrelic.NewApplication(
       newrelic.ConfigAppName("New Logrus Log Decorating"),
       newrelic.ConfigFromEnvironment(),
	newrelic.ConfigAppLogForwardingEnabled(false),				(2)	
	newrelic.ConfigAppLogDecoratingEnabled(true),  				(3)
   )
   if nil != err {
       log.Panic("Failed to create application", err)
   }
 
   log := logrus.New()
   log.SetFormatter(nrlogrus.NewFormatter(app, &logrus.TextFormatter{}))   	(4)
   log.Info("application connected to New Relic")
 
   return app, log
}
```

First, add and import the `logcontext-v2/nrlogrus` package to your app (1). Be aware that this does require you to upgrade the version of the go-agent to v3.17.1. Next, disable automatic log forwarding in the agent application configuration settings to avoid duplicating the logs you send to New Relic (2). You will also need to enable local log decorating (3). Once you set up a go-agent application and initialize a Logrus logger, set the logger’s formatter to a `nrlogrus` formatter. The `nrlogrus.NewFormatter()` convenience function needs to be passed a valid go-agent application, as well as any Logrus formatter of your choice.

There are a few notable differences in how the new plugin decorates logs. The log decorator you pass the plugin will determine how logrus writes each log line. Then, each log line is appended with metadata that links each log line to a specific New Relic project, and transaction when possible. Unlike the formatted JSON that the legacy plugin outputs, the end result is much more human readable, and the log line will be captured in New Relic One exactly as written by the log formatter of your choice. The log line from the example above would look like.

What the output will look like:
```
time="2022-07-22T01:02:21Z" level=info msg="application connected to New Relic" NR-LINKING|<your entity GUID>|<your hostname>|"New Logrus Log Decorating"|
```

What the message looks like in New Relic One:
```
time="2022-07-22T01:02:21Z" level=info msg="application connected to New Relic" 
```
