### ISSUE TITLE
Pass Transaction Attributes to Errors

### ISSUE THREAD

**Issue by arhea** [newrelic/go-agent#588]
Today transaction attributes are not passed to errors created during that transaction. This feature would add the attributes from the transaction to errors created with the `NoticeError` function.

[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Today when you add attributes to a transaction:

```go
newRelicTx := factories.NewRelicClient().StartTransaction(opts.Name)
defer newRelicTx.End()

newRelicTx.AddAttribute("job_id", job.ID())
newRelicTx.AddAttribute("job_project_id", job.ProjectID())
newRelicTx.AddAttribute("job_location", job.Location())
```

Then call an error like

```go
newRelicTx.NoticeError(newrelic.Error{
  Class:   "SomeError",
  Message:"something went wrong",
})
```

The attributes set on the transaction are not available on the error within the NewRelic dashboard.

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behaviour

Use transaction attributes as the base attributes on the error, then allow override of those values via the attributes object on the `NoticeError` function.

## Possible Solution

See above.

## Additional context

None.

**Comment by iamemilio** [comment]
I am not sure this is necessary. Errors are their own data type that are linked to transactions and spans by ID. This would just duplicate that data. This enhancement request might make more sense agains the New Relic UI. New Relic is moving to [public JIRA](issues.newrelic.com), rather than GitHub for issue tracking. I would recommend making an account there and filing this as a public feature request. Thanks!
