### ISSUE TITLE
Native Golang Profiling

### ISSUE THREAD

**Issue by frankgreco** [newrelic/go-agent#60]
When I think about assessing the behavior of goroutines, memory, cpu, etc. in the context of go, native golang profiling is the first thing I think about. There are many open source tools that use the raw data that is produced by the golang profile and turn it into meaningful graph (uber's [go-touch](https://uber.github.io/gotorch/) comes to mind).

I briefly browsed through the code and it doesn't look like New Relic is utilizing native golang profiling but instead implementing their own (If I am wrong please correct me). However, if I am right, could you provide context as to why New Relic is solving the problem in the way as opposed to using the native tools the language provides?

**Comment by sergeylanzman** [comment]
https://github.com/newrelic/go-agent/issues/30

**Comment by vinhnewrelic** [comment]
Hi Frank,

Thanks for your feedback! I created a new FR for this and linked it to [30](https://github.com/newrelic/go-agent/issues/30) since there are some similarities. You're right that leveraging native profiling can create a compelling story for our Go users and it's something I want to explore more with the team.

Vinh
