### ISSUE TITLE
RecordCustomEvent does not return error, even though event was not recorded

### ISSUE THREAD

**Issue by vivekv96** [newrelic/go-agent#94]
Hi,
I am trying to record custom events.
Please refer the following snippet - 

```
var app newrelic.Application

func init() {
    var err error
    conf := newrelic.NewConfig(os.Getenv("NEWRELIC_APPNAME"), os.Getenv("NEWRELIC_LICENSE"))
    app, err = newrelic.NewApplication(conf)
    if err != nil {
        log.Println("error in creating new relic application: ", err)
    }
}

func recordCustomNewRelicEvent(customAttribute int) {
    if err := app.RecordCustomEvent("Transaction", map[string]interface{}{
        "randomCustomAttribute": customAttribute,
    }); err != nil {
        log.Println("error in creating New Relic custom event: ", err)
        return
    }

    app.Shutdown(5 * time.Second)
}
```

The first call to `recordCustomNewRelicEvent()`, records an event, I can see it in the Insights dashboard that I created, I can also see the event when I run the following NRQL query -
 ```SELECT * FROM Transaction```.

But, the subsequent calls to `recordCustomNewRelicEvent()` do not record any events and the returned `err` variable from `app.RecordCustomEvent()` is `nil`.

Is it because of the `app.Shutdown()` encountered in the previous call? 
If so, why is the `err` variable `nil`.

Am I missing something?
Thank you in advance, for any help regarding this.

**Comment by willnewrelic** [comment]
Hi @vivekv96 

Yes, the subsequent calls to `app.RecordCustomEvent` fail because they occur after `app.Shutdown`.  No data will be collected after `Shutdown` is called.  It is designed to be used only when the entire process is shutting down.

I acknowledge that not returning an error is confusing!  That would be an improvement.  I have recorded this in an internal issue.  Thanks for bringing this to our attention.
